---
title: "Estatística Aplicada em Agronomia utilizando o Software R"
author: "Juliana Moraes Machado de Oliveira e Milene Venancio Soré"
output: 
 html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
---

<style type="text/css">

*{
font-size: 16px;
font-family: 'times new roman';
text-align: justify;
color: black;
}

h1 {color: darkgreen;
    text-align: center;
    font-family: Impact;
    font-size: 40px;
}

code.r, pre {font-size: 14px;
    margin-left: auto;
    margin-right: auto;
    width: 100%;
    background-color: lightyellow;
    border: white;

</style>

<style>
#TOC {
  background: url("https://redacaonline.com.br/blog/wp-content/uploads/2018/02/logo_uel.jpg");
  background-size: contain;
  padding-top: 100px !important;
  background-repeat: no-repeat;
}
</style>
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, fig.align = "center", message = FALSE,warning = FALSE, fig.width = 12,fig.height = 12)
library(knitr)
options(knitr.kable.NA="")
```
# Prefácio

# 1. Introdução à Estatística 

## 1.1 Definição
A Estatística é uma ciência exata que estuda métodos de análise de dados experimentais para auxiliar em tomadas de decisões. As análises estatísticas dependem da forma de como ocorre a coleta desses dados, ou seja, como transcorre o método estatístico. Assim, a estatística consiste no estudo, utilizando um conjunto de técnicas úteis, para chegar à conclusões sobre uma população, partindo da análise das informações contidas nas observações dos dados de uma amostra.

Deste modo, a estatística está diariamente presente no mundo, em diversas áreas de conhecimento, como pesquisas de opniões públicas, estudos observacionais e experimentação. Assim, essa ciência é encontrada, por exemplo, em pesquisas eleitorais, verificações de qualidade de ensino, taxa de propagação de doenças e, principalmente, no âmbito agrícola, em sintuações em que se deseja comparar produtividades de variedades, estimativar a produção na colheita das safras, prever fenômenos meteorológicos, entre outros.  

## 1.2 Aplicabilidade da Estatística nas Ciências Agrárias - CÓPIA!!!! (EDITAR DPS)

2.2 Importância  
A  estatística  agrícola  proporciona  uma  melhor  apreciação  e  avaliação  da  situação  da  agricultura  na  economia  para  quem  está  envolvido.  Ela  ajuda  a  reunir  informações  que  auxiliam  na  formulação  de  políticas  públicas,   assim  como  no  planejamento  e  na  tomada  de decisões pelas instituições governamentais (CASER, 2009)  A  estatística  t ambém  fornece  dados  básicos  par a  a  pesquisa  científica  e  a  extensão  rural,  em  especial  no  campo  socioeconômico  e  informações  a  entidades  privadas  e   aos agricultores afins de auxiliá-los no planejamento de suas atividades (CASER, 2009).2.2 Importância  A  estatística  agrícola  proporciona  uma  melhor  apreciação  e  avaliação  da  situação  da  agricultura  na  economia  para  quem  está  envolvido.  Ela  ajuda  a  reunir  informações  que  auxiliam  na  formulação  de  políticas  públicas,   assim  como  no  planejamento  e  na  tomada  de decisões pelas instituições governamentais (CASER, 2009)  A  estatística  t ambém  fornece  dados  básicos  par a  a  pesquisa  científica  e  a  extensão  rural,  em  especial  no  campo  socioeconômico  e  informações  a  entidades  privadas  e   aos agricultores afins de auxiliá-los no planejamento de suas atividades (CASER, 2009).

2.3 Principais usos na agricultura  
O uso da  estatística na ag ronomia é de suma  importância, utilizado pa ra analisar banco de  dados,  planejar  palestras,  workshops,  contribuindo  para  o  profissional  obter  informações de dados,  projetos  e  pesquisas,  tudo  isso  com  o  objetivo  de  melhorar  a prod ução da  lavoura,  e  compartilhar o conhecimento para outros na area (DUARTE, 2016). A estatística é o meio principal usado na agricultura, ela é importante para se realizar diversos projetos e cálculos. Veja alguns exemplos de uso da estatística em meio rural (DUARTE, 2016).

Consultoria:  O  consultor  de  dados  usa  a  estatística  para  examinar   uma  certa  propriedade  que,  por exemplo, está  produzindo  grãos em  grande  escala,  mas  apresentando um  alto  custo  no  manejo da  produção.  Existem  empresas  especializados  na  prestação  de  serviços  de  consultoria  que  atende tal demanda de produtores rurais, pecuaristas e agricultores.

Vendas de Insumos:  Pode  ser  aplic ado  no  plano  de  venda,  indicando  assim  os  produtos  de  melhor  rentabilidade em grande escala para definição de  estoque. Realizando o processo de  promoção de vendas, por se fazer a orientação técnica a produtores, distribuidores e revendas. 

Pesquisas de plantas:  Esta  é  uma  das  áreas  da  agronomia  em  que  a  estatística  é  mais  usada,  um  dos exemplos  disso  é  o  plantio  de  uma  espécie  de  planta,  analisando  o  desenvolvimento  de folhagem,  fruto,  raiz  e  melhor  crescimento,  buscando  controlar  plantas  daninhas  e  o melhoramento genético. 

Administração de uma propriedade rural:  Um  administrador  rural  utiliza  a  estatística  ba sicamente  em  todo  o  seu  processo administrativo  de  uma  propriedade,  d esde  planos  de  metas  anuais,   recrutamento  d e funcionários,  análise  de  banco  d e  dados  pa ra  obter  respostas  futuras,  t ais  como  faturamento  anual, rentabilidade, gastos planejamento de produção em grande escala
FONTE: https://www.passeidireto.com/arquivo/90740880/aplicacoes-da-estatistica-em-ciencias-agrarias
-----------------------------------------
As estatísticas agrícolas proporcionam melhor apreciação e avaliação da situação da agricultura na economia pelos agentes envolvidos. Reúnem informações que subsidiam a formulação de políticas públicas, bem como auxiliam no planejamento e na tomada de decisões pelas instituições governamentais; fornecem dados básicos para a pesquisa científica e para a extensão rural, em especial no campo sócio-econômico e informações a entidades privadas e aos agricultores para auxiliá-los no planejamento de suas atividades.
FONTE: http://www.iea.sp.gov.br/out/verTexto.php?codTexto=11758

## 1.3 Áreas da Estatística
ESTATISTICA: DESCRITIVA  X  INFERÊNCIA


## 1.4 Fases do Método Estatístico
https://bibliotecadigital.saraivaeducacao.com.br/epub/600594?title=ESTAT%C3%8DSTICA%20F%C3%81CIL -> "etapas de uma pesquisa" (caderno do biz)

1. Planejamento
2. Perguntas
3. Coleta de dados
4. Análise estatística e apresentação dos resultados
5. Conclusão

## 1.5 Conceitos Fundamentais
O que é:
- parâmetro
- estatística
- variáveis
- dados

## 1.6 Classificação das Variáveis
Variáveis: qualitativas X quantitativas

## 1.7 Amostragem
- O que é uma população?
- O que é uma amostra?
- Como se obtém uma amostra?
- Tipos de Amostragem:
 # Aleatória Simples
 # Sistemática
 # Aleatória Estratifica
 # Amostragem por Conglomerados
 # Amostragem por Conveniência
 # Amostragem por quotas
- Dimensionamento Amostral


$$$$$$$$$$ Referências para montagem de textos/questões do primeiro capítulo:
https://www.ifmg.edu.br/conselheirolafaiete/noticias/anexos-noticias/apostila-introducao-a-estatistica-ifmg-cl.pdf
http://leg.ufpr.br/~silvia/CE055/node8.html

--------------------------------------------------------------------------------

# 2. Introdução ao Software R

## 2.1 Definição

## 2.2 Características do Programa

## 2.3 Pacotes do R

## 2.4 O RStudio

## 2.5 Instalação do R, R Studio e Pacotes

## 2.6 Projetos R

## 2.7 Operadores do R

## 2.8 Funções Matemáticas do R

## 2.9 Importação de dados, tabelas e imagens

-------------------------------------------------------------------------------

# 3. Análise Exploratória de Dados

## 3.1 A Estatística Descritiva

## 3.2 Tabelas
(falar dos tipos de tabelas e como elas são formadas)
(falar como se monta tabelas no R)
(exercícios de tabelas)
FONTE: http://alexandreprofessor.blogspot.com/p/tabelas.html

## 3.3 Distribuição de Frequências

## 3.4 Gráficos

## 3.5 Medidas de Posição
(média, mediana e moda)

## 3.6 Medidas Separatrizes 
(mediana, quartis, decis, etc...)
(falar do gráfico de caixas - boxplot)

## 3.7 Medidas de Dispersão
(variância, desvio, etc)

## 3.8 Análise Bidimensional 

## 3.9 Medidas de Associação 


--------------------------------------------------------------------------------


# Probabilidade e modelos de probabilidade



# Introdução em inferência estatística



# Testes de hipóteses



# Planejamento e análise de experimentos


# Regressão linear simples e múltipla






# Referências Bibliográficas
https://www.ibilce.unesp.br/Home/Departamentos/CiencCompEstatistica/Adriana/conceitos-basicos---estatistica.pdf
http://www.leg.ufpr.br/~silvia/CE001/node3.html
Estatística Aplicada. VIRGILLITO, S. B.
Estatística Fácil. CRESPO, A. A.
